[libraries]

components.files = [
  "components/**/*.vhdl"
]

components_testbench.files = [
  "components_testbenches/**/*.vhdl"
]

week1.files = [
  "week1/rtl/*.vhdl",
  "week1/simulation/*.vhdl"
]

week2.files = [
  "week2/rtl/*.vhdl",
  "week2/simulation/*.vhdl"
]

week3.files = [
  "week3/rtl/*.vhdl",
  "week3/simulation/*.vhdl"
]
